// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljhqyifbbdvrvasercgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqaHF5aWZiYmR2cnZhc2VyY2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMzIzMzQsImV4cCI6MjA3NDgwODMzNH0.CSaAk9QhTpBurxlMAhcC-pd_r7RH8a4lgxjOy9QsbYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});